apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: mico-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: demoteam88/order-services:latest
        env:
        - name: PORT
          value: "3002"
        - name: NODE_ENV
          value: "development"
        - name: DEBUG
          value: "*"
        - name: LOG_LEVEL
          value: "debug"
        - name: USER_SERVICE_URL
          value: "http://user-service.mico-k8s.svc.cluster.local:3000"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service.mico-k8s.svc.cluster.local:3001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 3002