apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: mico-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: demoteam88/product-services:latest
        env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "development"
        - name: DEBUG
          value: "*"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 3001