apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mico-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: demoteam88/user-service:latest
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "development"
        - name: DEBUG
          value: "*"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
