apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: mico-k8s
spec:
  selector:
    app: gateway-service
  ports:
  - port: 3003
    protocol: TCP 
    targetPort: 3003
  type: ClusterIP
