apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: mico-k8s
spec:
  selector:
    app: order-service
  ports:
  - port: 3002
    protocol: TCP 
    targetPort: 3002
  type: ClusterIP
