apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: mico-k8s
spec:
  selector:
    app: product-service
  ports:
  - port: 3001
    protocol: TCP 
    targetPort: 3001
  type: ClusterIP
