apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mico-k8s
  labels:
    app: user-service
    tier: backend
spec:
  selector:
    app: user-service
  ports:
  - port: 3000
    protocol: TCP 
    targetPort: 3000
  type: ClusterIP
